### PR TITLE
Chapter 1 to Chapter 7 exercises - I modified the commit messages for each chapter, so that each commit message reflects a chapter

### PR DESCRIPTION
**Pull request by lkmandy**

### CODE REVIEW

**Comment by Izakey** [comment]
@mandylk You need to learn how to ignore files using .gitignore

**Comment by Izakey** [comment]
@mandylk I've a few questions for you. 
1. Why did you close this Pull Request ? Kindly reopen it asap.
2. Why do your commits include Chapter 1 to 5 exercises given that you've already done that earlier ?

**Comment by lkmandy** [comment]
1. I closed it in error
2. I re-setted my local repository because I wanted my git log history to be clean and to also modify the commit messages so that the match each chapter

**Comment by lkmandy** [comment]
I just noticed I did not close the pull request.
It happened because I had done a force push to update my local repo as I explained above
I think I can re-open it if you give me rights to re-open pull requests

**Comment by Izakey** [comment]
You have the appropriate karma to reopen a PR which you indeed closed
(albeit mistakenly)

**Comment by Izakey** [comment]
@mandylk You've closed this PR without it being merged into the repo. The way forward is sending in a new PR so I review and merge.

**Pull request closed without merging**
